// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: sort_node.proto

package sortmistake

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED  NodeType = 0
	NodeType_NODE_TYPE_HUB          NodeType = 1
	NodeType_NODE_TYPE_MIDDLE       NodeType = 2
	NodeType_NODE_TYPE_ZONE         NodeType = 3
	NodeType_NODE_TYPE_INTRA_INPUT  NodeType = 4
	NodeType_NODE_TYPE_INTRA_MID    NodeType = 5
	NodeType_NODE_TYPE_INTRA_OUTPUT NodeType = 6
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_HUB",
		2: "NODE_TYPE_MIDDLE",
		3: "NODE_TYPE_ZONE",
		4: "NODE_TYPE_INTRA_INPUT",
		5: "NODE_TYPE_INTRA_MID",
		6: "NODE_TYPE_INTRA_OUTPUT",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED":  0,
		"NODE_TYPE_HUB":          1,
		"NODE_TYPE_MIDDLE":       2,
		"NODE_TYPE_ZONE":         3,
		"NODE_TYPE_INTRA_INPUT":  4,
		"NODE_TYPE_INTRA_MID":    5,
		"NODE_TYPE_INTRA_OUTPUT": 6,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{0}
}

type NodeEvent int32

const (
	NodeEvent_NODE_EVENT_UNSPECIFIED NodeEvent = 0
	NodeEvent_NODE_EVENT_CREATED     NodeEvent = 1
	NodeEvent_NODE_EVENT_UPDATED     NodeEvent = 2
	NodeEvent_NODE_EVENT_DELETED     NodeEvent = 3
)

// Enum value maps for NodeEvent.
var (
	NodeEvent_name = map[int32]string{
		0: "NODE_EVENT_UNSPECIFIED",
		1: "NODE_EVENT_CREATED",
		2: "NODE_EVENT_UPDATED",
		3: "NODE_EVENT_DELETED",
	}
	NodeEvent_value = map[string]int32{
		"NODE_EVENT_UNSPECIFIED": 0,
		"NODE_EVENT_CREATED":     1,
		"NODE_EVENT_UPDATED":     2,
		"NODE_EVENT_DELETED":     3,
	}
)

func (x NodeEvent) Enum() *NodeEvent {
	p := new(NodeEvent)
	*p = x
	return p
}

func (x NodeEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[1].Descriptor()
}

func (NodeEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[1]
}

func (x NodeEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEvent.Descriptor instead.
func (NodeEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{1}
}

type NodeEventType int32

const (
	NodeEventType_NODE_EVENT_TYPE_UNSPECIFIED NodeEventType = 0
	NodeEventType_NODE_EVENT_TYPE_INTERNAL    NodeEventType = 1
	NodeEventType_NODE_EVENT_TYPE_EXTERNAL    NodeEventType = 2
)

// Enum value maps for NodeEventType.
var (
	NodeEventType_name = map[int32]string{
		0: "NODE_EVENT_TYPE_UNSPECIFIED",
		1: "NODE_EVENT_TYPE_INTERNAL",
		2: "NODE_EVENT_TYPE_EXTERNAL",
	}
	NodeEventType_value = map[string]int32{
		"NODE_EVENT_TYPE_UNSPECIFIED": 0,
		"NODE_EVENT_TYPE_INTERNAL":    1,
		"NODE_EVENT_TYPE_EXTERNAL":    2,
	}
)

func (x NodeEventType) Enum() *NodeEventType {
	p := new(NodeEventType)
	*p = x
	return p
}

func (x NodeEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[2].Descriptor()
}

func (NodeEventType) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[2]
}

func (x NodeEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEventType.Descriptor instead.
func (NodeEventType) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{2}
}

type NodeError int32

const (
	NodeError_NODE_ERROR_UNSPECIFIED NodeError = 0
	NodeError_NODE_ERROR_DATABASE    NodeError = 1
	NodeError_NODE_ERROR_REDIS       NodeError = 2
	NodeError_NODE_ERROR_KAFKA       NodeError = 3
)

// Enum value maps for NodeError.
var (
	NodeError_name = map[int32]string{
		0: "NODE_ERROR_UNSPECIFIED",
		1: "NODE_ERROR_DATABASE",
		2: "NODE_ERROR_REDIS",
		3: "NODE_ERROR_KAFKA",
	}
	NodeError_value = map[string]int32{
		"NODE_ERROR_UNSPECIFIED": 0,
		"NODE_ERROR_DATABASE":    1,
		"NODE_ERROR_REDIS":       2,
		"NODE_ERROR_KAFKA":       3,
	}
)

func (x NodeError) Enum() *NodeError {
	p := new(NodeError)
	*p = x
	return p
}

func (x NodeError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeError) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[3].Descriptor()
}

func (NodeError) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[3]
}

func (x NodeError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeError.Descriptor instead.
func (NodeError) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{3}
}

type PathEvent int32

const (
	PathEvent_PATH_EVENT_UNSPECIFIED PathEvent = 0
	PathEvent_PATH_EVENT_CREATED     PathEvent = 1
	PathEvent_PATH_EVENT_UPDATED     PathEvent = 2
	PathEvent_PATH_EVENT_DELETED     PathEvent = 3
)

// Enum value maps for PathEvent.
var (
	PathEvent_name = map[int32]string{
		0: "PATH_EVENT_UNSPECIFIED",
		1: "PATH_EVENT_CREATED",
		2: "PATH_EVENT_UPDATED",
		3: "PATH_EVENT_DELETED",
	}
	PathEvent_value = map[string]int32{
		"PATH_EVENT_UNSPECIFIED": 0,
		"PATH_EVENT_CREATED":     1,
		"PATH_EVENT_UPDATED":     2,
		"PATH_EVENT_DELETED":     3,
	}
)

func (x PathEvent) Enum() *PathEvent {
	p := new(PathEvent)
	*p = x
	return p
}

func (x PathEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[4].Descriptor()
}

func (PathEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[4]
}

func (x PathEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathEvent.Descriptor instead.
func (PathEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{4}
}

type ZoneFilterEvent int32

const (
	ZoneFilterEvent_ZONE_FILTER_EVENT_UNSPECIFIED ZoneFilterEvent = 0
	ZoneFilterEvent_ZONE_FILTER_EVENT_CREATED     ZoneFilterEvent = 1
	ZoneFilterEvent_ZONE_FILTER_EVENT_UPDATED     ZoneFilterEvent = 2
	ZoneFilterEvent_ZONE_FILTER_EVENT_DELETED     ZoneFilterEvent = 3
)

// Enum value maps for ZoneFilterEvent.
var (
	ZoneFilterEvent_name = map[int32]string{
		0: "ZONE_FILTER_EVENT_UNSPECIFIED",
		1: "ZONE_FILTER_EVENT_CREATED",
		2: "ZONE_FILTER_EVENT_UPDATED",
		3: "ZONE_FILTER_EVENT_DELETED",
	}
	ZoneFilterEvent_value = map[string]int32{
		"ZONE_FILTER_EVENT_UNSPECIFIED": 0,
		"ZONE_FILTER_EVENT_CREATED":     1,
		"ZONE_FILTER_EVENT_UPDATED":     2,
		"ZONE_FILTER_EVENT_DELETED":     3,
	}
)

func (x ZoneFilterEvent) Enum() *ZoneFilterEvent {
	p := new(ZoneFilterEvent)
	*p = x
	return p
}

func (x ZoneFilterEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneFilterEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[5].Descriptor()
}

func (ZoneFilterEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[5]
}

func (x ZoneFilterEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneFilterEvent.Descriptor instead.
func (ZoneFilterEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{5}
}

type OrderTagFilterEvent int32

const (
	OrderTagFilterEvent_ORDER_TAG_FILTER_EVENT_UNSPECIFIED OrderTagFilterEvent = 0
	OrderTagFilterEvent_ORDER_TAG_FILTER_EVENT_CREATED     OrderTagFilterEvent = 1
	OrderTagFilterEvent_ORDER_TAG_FILTER_EVENT_UPDATED     OrderTagFilterEvent = 2
	OrderTagFilterEvent_ORDER_TAG_FILTER_EVENT_DELETED     OrderTagFilterEvent = 3
)

// Enum value maps for OrderTagFilterEvent.
var (
	OrderTagFilterEvent_name = map[int32]string{
		0: "ORDER_TAG_FILTER_EVENT_UNSPECIFIED",
		1: "ORDER_TAG_FILTER_EVENT_CREATED",
		2: "ORDER_TAG_FILTER_EVENT_UPDATED",
		3: "ORDER_TAG_FILTER_EVENT_DELETED",
	}
	OrderTagFilterEvent_value = map[string]int32{
		"ORDER_TAG_FILTER_EVENT_UNSPECIFIED": 0,
		"ORDER_TAG_FILTER_EVENT_CREATED":     1,
		"ORDER_TAG_FILTER_EVENT_UPDATED":     2,
		"ORDER_TAG_FILTER_EVENT_DELETED":     3,
	}
)

func (x OrderTagFilterEvent) Enum() *OrderTagFilterEvent {
	p := new(OrderTagFilterEvent)
	*p = x
	return p
}

func (x OrderTagFilterEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderTagFilterEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[6].Descriptor()
}

func (OrderTagFilterEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[6]
}

func (x OrderTagFilterEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderTagFilterEvent.Descriptor instead.
func (OrderTagFilterEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{6}
}

type OutputNodeEvent int32

const (
	OutputNodeEvent_OUTPUT_NODE_EVENT_UNSPECIFIED OutputNodeEvent = 0
	OutputNodeEvent_OUTPUT_NODE_EVENT_CREATED     OutputNodeEvent = 1
	OutputNodeEvent_OUTPUT_NODE_EVENT_UPDATED     OutputNodeEvent = 2
	OutputNodeEvent_OUTPUT_NODE_EVENT_DELETED     OutputNodeEvent = 3
)

// Enum value maps for OutputNodeEvent.
var (
	OutputNodeEvent_name = map[int32]string{
		0: "OUTPUT_NODE_EVENT_UNSPECIFIED",
		1: "OUTPUT_NODE_EVENT_CREATED",
		2: "OUTPUT_NODE_EVENT_UPDATED",
		3: "OUTPUT_NODE_EVENT_DELETED",
	}
	OutputNodeEvent_value = map[string]int32{
		"OUTPUT_NODE_EVENT_UNSPECIFIED": 0,
		"OUTPUT_NODE_EVENT_CREATED":     1,
		"OUTPUT_NODE_EVENT_UPDATED":     2,
		"OUTPUT_NODE_EVENT_DELETED":     3,
	}
)

func (x OutputNodeEvent) Enum() *OutputNodeEvent {
	p := new(OutputNodeEvent)
	*p = x
	return p
}

func (x OutputNodeEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputNodeEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[7].Descriptor()
}

func (OutputNodeEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[7]
}

func (x OutputNodeEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputNodeEvent.Descriptor instead.
func (OutputNodeEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{7}
}

type MapEvent int32

const (
	MapEvent_MAP_EVENT_UNSPECIFIED MapEvent = 0
	MapEvent_MAP_EVENT_CREATED     MapEvent = 1
	MapEvent_MAP_EVENT_UPDATED     MapEvent = 2
	MapEvent_MAP_EVENT_DELETED     MapEvent = 3
)

// Enum value maps for MapEvent.
var (
	MapEvent_name = map[int32]string{
		0: "MAP_EVENT_UNSPECIFIED",
		1: "MAP_EVENT_CREATED",
		2: "MAP_EVENT_UPDATED",
		3: "MAP_EVENT_DELETED",
	}
	MapEvent_value = map[string]int32{
		"MAP_EVENT_UNSPECIFIED": 0,
		"MAP_EVENT_CREATED":     1,
		"MAP_EVENT_UPDATED":     2,
		"MAP_EVENT_DELETED":     3,
	}
)

func (x MapEvent) Enum() *MapEvent {
	p := new(MapEvent)
	*p = x
	return p
}

func (x MapEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[8].Descriptor()
}

func (MapEvent) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[8]
}

func (x MapEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapEvent.Descriptor instead.
func (MapEvent) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{8}
}

type MapError int32

const (
	MapError_MAP_ERROR_UNSPECIFIED MapError = 0
	MapError_MAP_ERROR_GENERATE    MapError = 1
	MapError_MAP_ERROR_STORE       MapError = 2
	MapError_MAP_ERROR_PUBLISH     MapError = 3
)

// Enum value maps for MapError.
var (
	MapError_name = map[int32]string{
		0: "MAP_ERROR_UNSPECIFIED",
		1: "MAP_ERROR_GENERATE",
		2: "MAP_ERROR_STORE",
		3: "MAP_ERROR_PUBLISH",
	}
	MapError_value = map[string]int32{
		"MAP_ERROR_UNSPECIFIED": 0,
		"MAP_ERROR_GENERATE":    1,
		"MAP_ERROR_STORE":       2,
		"MAP_ERROR_PUBLISH":     3,
	}
)

func (x MapError) Enum() *MapError {
	p := new(MapError)
	*p = x
	return p
}

func (x MapError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapError) Descriptor() protoreflect.EnumDescriptor {
	return file_sort_node_proto_enumTypes[9].Descriptor()
}

func (MapError) Type() protoreflect.EnumType {
	return &file_sort_node_proto_enumTypes[9]
}

func (x MapError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapError.Descriptor instead.
func (MapError) EnumDescriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{9}
}

type SortNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RealId            int64                  `protobuf:"varint,3,opt,name=real_id,json=realId,proto3" json:"real_id,omitempty"`
	HubId             int64                  `protobuf:"varint,4,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type              NodeType               `protobuf:"varint,6,opt,name=type,proto3,enum=protos.sort.sortmistake.NodeType" json:"type,omitempty"`
	SystemId          string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	RejectionCriteria uint32                 `protobuf:"varint,11,opt,name=rejection_criteria,json=rejectionCriteria,proto3" json:"rejection_criteria,omitempty"`
	CompatId          int64                  `protobuf:"varint,51,opt,name=compat_id,json=compatId,proto3" json:"compat_id,omitempty"`
	NodeEvent         NodeEvent              `protobuf:"varint,101,opt,name=node_event,json=nodeEvent,proto3,enum=protos.sort.sortmistake.NodeEvent" json:"node_event,omitempty"`
	Error             NodeError              `protobuf:"varint,200,opt,name=error,proto3,enum=protos.sort.sortmistake.NodeError" json:"error,omitempty"`
	RetryCount        int32                  `protobuf:"varint,202,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryDatetime     uint64                 `protobuf:"varint,203,opt,name=retry_datetime,json=retryDatetime,proto3" json:"retry_datetime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SortNode) Reset() {
	*x = SortNode{}
	mi := &file_sort_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortNode) ProtoMessage() {}

func (x *SortNode) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortNode.ProtoReflect.Descriptor instead.
func (*SortNode) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{0}
}

func (x *SortNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SortNode) GetRealId() int64 {
	if x != nil {
		return x.RealId
	}
	return 0
}

func (x *SortNode) GetHubId() int64 {
	if x != nil {
		return x.HubId
	}
	return 0
}

func (x *SortNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SortNode) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *SortNode) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortNode) GetRejectionCriteria() uint32 {
	if x != nil {
		return x.RejectionCriteria
	}
	return 0
}

func (x *SortNode) GetCompatId() int64 {
	if x != nil {
		return x.CompatId
	}
	return 0
}

func (x *SortNode) GetNodeEvent() NodeEvent {
	if x != nil {
		return x.NodeEvent
	}
	return NodeEvent_NODE_EVENT_UNSPECIFIED
}

func (x *SortNode) GetError() NodeError {
	if x != nil {
		return x.Error
	}
	return NodeError_NODE_ERROR_UNSPECIFIED
}

func (x *SortNode) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SortNode) GetRetryDatetime() uint64 {
	if x != nil {
		return x.RetryDatetime
	}
	return 0
}

type SortPath struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId        int64                  `protobuf:"varint,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId   int64                  `protobuf:"varint,2,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	Id                  int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	HubId               int64                  `protobuf:"varint,5,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	SystemId            string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Distance            uint32                 `protobuf:"varint,10,opt,name=distance,proto3" json:"distance,omitempty"`
	RejectionConditions uint32                 `protobuf:"varint,11,opt,name=rejection_conditions,json=rejectionConditions,proto3" json:"rejection_conditions,omitempty"`
	// Deprecated: Marked as deprecated in sort_node.proto.
	ZoneFilters        []int64               `protobuf:"varint,12,rep,packed,name=zone_filters,json=zoneFilters,proto3" json:"zone_filters,omitempty"` // deprecated: LM-only
	Label              string                `protobuf:"bytes,21,opt,name=label,proto3" json:"label,omitempty"`
	ZoneFilterRefs     []*PathZoneFilter     `protobuf:"bytes,22,rep,name=zone_filter_refs,json=zoneFilterRefs,proto3" json:"zone_filter_refs,omitempty"`
	OrderTagFilterRefs []*PathOrderTagFilter `protobuf:"bytes,23,rep,name=order_tag_filter_refs,json=orderTagFilterRefs,proto3" json:"order_tag_filter_refs,omitempty"`
	PathEvent          PathEvent             `protobuf:"varint,101,opt,name=path_event,json=pathEvent,proto3,enum=protos.sort.sortmistake.PathEvent" json:"path_event,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SortPath) Reset() {
	*x = SortPath{}
	mi := &file_sort_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortPath) ProtoMessage() {}

func (x *SortPath) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortPath.ProtoReflect.Descriptor instead.
func (*SortPath) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{1}
}

func (x *SortPath) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *SortPath) GetDestinationNodeId() int64 {
	if x != nil {
		return x.DestinationNodeId
	}
	return 0
}

func (x *SortPath) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SortPath) GetHubId() int64 {
	if x != nil {
		return x.HubId
	}
	return 0
}

func (x *SortPath) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortPath) GetDistance() uint32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SortPath) GetRejectionConditions() uint32 {
	if x != nil {
		return x.RejectionConditions
	}
	return 0
}

// Deprecated: Marked as deprecated in sort_node.proto.
func (x *SortPath) GetZoneFilters() []int64 {
	if x != nil {
		return x.ZoneFilters
	}
	return nil
}

func (x *SortPath) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SortPath) GetZoneFilterRefs() []*PathZoneFilter {
	if x != nil {
		return x.ZoneFilterRefs
	}
	return nil
}

func (x *SortPath) GetOrderTagFilterRefs() []*PathOrderTagFilter {
	if x != nil {
		return x.OrderTagFilterRefs
	}
	return nil
}

func (x *SortPath) GetPathEvent() PathEvent {
	if x != nil {
		return x.PathEvent
	}
	return PathEvent_PATH_EVENT_UNSPECIFIED
}

type PathZoneFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        int64                  `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneType      string                 `protobuf:"bytes,2,opt,name=zone_type,json=zoneType,proto3" json:"zone_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathZoneFilter) Reset() {
	*x = PathZoneFilter{}
	mi := &file_sort_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathZoneFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathZoneFilter) ProtoMessage() {}

func (x *PathZoneFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathZoneFilter.ProtoReflect.Descriptor instead.
func (*PathZoneFilter) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{2}
}

func (x *PathZoneFilter) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *PathZoneFilter) GetZoneType() string {
	if x != nil {
		return x.ZoneType
	}
	return ""
}

type PathOrderTagFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderTagId    int64                  `protobuf:"varint,1,opt,name=order_tag_id,json=orderTagId,proto3" json:"order_tag_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathOrderTagFilter) Reset() {
	*x = PathOrderTagFilter{}
	mi := &file_sort_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathOrderTagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathOrderTagFilter) ProtoMessage() {}

func (x *PathOrderTagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathOrderTagFilter.ProtoReflect.Descriptor instead.
func (*PathOrderTagFilter) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{3}
}

func (x *PathOrderTagFilter) GetOrderTagId() int64 {
	if x != nil {
		return x.OrderTagId
	}
	return 0
}

func (x *PathOrderTagFilter) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type SortMap struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ZoneId              int64                  `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneNodeId          int64                  `protobuf:"varint,2,opt,name=zone_node_id,json=zoneNodeId,proto3" json:"zone_node_id,omitempty"`
	SourceNodeId        int64                  `protobuf:"varint,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId   int64                  `protobuf:"varint,6,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	SystemId            string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Distance            uint32                 `protobuf:"varint,10,opt,name=distance,proto3" json:"distance,omitempty"`
	AdjustedDistance    uint32                 `protobuf:"varint,11,opt,name=adjusted_distance,json=adjustedDistance,proto3" json:"adjusted_distance,omitempty"`
	RejectionConditions uint32                 `protobuf:"varint,12,opt,name=rejection_conditions,json=rejectionConditions,proto3" json:"rejection_conditions,omitempty"`
	Label               string                 `protobuf:"bytes,21,opt,name=label,proto3" json:"label,omitempty"`
	MapEvent            MapEvent               `protobuf:"varint,101,opt,name=map_event,json=mapEvent,proto3,enum=protos.sort.sortmistake.MapEvent" json:"map_event,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SortMap) Reset() {
	*x = SortMap{}
	mi := &file_sort_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortMap) ProtoMessage() {}

func (x *SortMap) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortMap.ProtoReflect.Descriptor instead.
func (*SortMap) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{4}
}

func (x *SortMap) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *SortMap) GetZoneNodeId() int64 {
	if x != nil {
		return x.ZoneNodeId
	}
	return 0
}

func (x *SortMap) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *SortMap) GetDestinationNodeId() int64 {
	if x != nil {
		return x.DestinationNodeId
	}
	return 0
}

func (x *SortMap) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortMap) GetDistance() uint32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SortMap) GetAdjustedDistance() uint32 {
	if x != nil {
		return x.AdjustedDistance
	}
	return 0
}

func (x *SortMap) GetRejectionConditions() uint32 {
	if x != nil {
		return x.RejectionConditions
	}
	return 0
}

func (x *SortMap) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SortMap) GetMapEvent() MapEvent {
	if x != nil {
		return x.MapEvent
	}
	return MapEvent_MAP_EVENT_UNSPECIFIED
}

type ZoneFilter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemId             string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	HubId                int64                  `protobuf:"varint,3,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	SourceId             int64                  `protobuf:"varint,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId        int64                  `protobuf:"varint,5,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	ZoneId               int64                  `protobuf:"varint,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	RefRejectConditionId int64                  `protobuf:"varint,7,opt,name=ref_reject_condition_id,json=refRejectConditionId,proto3" json:"ref_reject_condition_id,omitempty"`
	ZoneType             string                 `protobuf:"bytes,8,opt,name=zone_type,json=zoneType,proto3" json:"zone_type,omitempty"`
	ZoneFilterEvent      ZoneFilterEvent        `protobuf:"varint,101,opt,name=zone_filter_event,json=zoneFilterEvent,proto3,enum=protos.sort.sortmistake.ZoneFilterEvent" json:"zone_filter_event,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ZoneFilter) Reset() {
	*x = ZoneFilter{}
	mi := &file_sort_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneFilter) ProtoMessage() {}

func (x *ZoneFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneFilter.ProtoReflect.Descriptor instead.
func (*ZoneFilter) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneFilter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ZoneFilter) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ZoneFilter) GetHubId() int64 {
	if x != nil {
		return x.HubId
	}
	return 0
}

func (x *ZoneFilter) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *ZoneFilter) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *ZoneFilter) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *ZoneFilter) GetRefRejectConditionId() int64 {
	if x != nil {
		return x.RefRejectConditionId
	}
	return 0
}

func (x *ZoneFilter) GetZoneType() string {
	if x != nil {
		return x.ZoneType
	}
	return ""
}

func (x *ZoneFilter) GetZoneFilterEvent() ZoneFilterEvent {
	if x != nil {
		return x.ZoneFilterEvent
	}
	return ZoneFilterEvent_ZONE_FILTER_EVENT_UNSPECIFIED
}

type OrderTagFilter struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemId            string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	HubId               int64                  `protobuf:"varint,3,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	SourceId            int64                  `protobuf:"varint,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId       int64                  `protobuf:"varint,5,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	OrderTagId          int64                  `protobuf:"varint,6,opt,name=order_tag_id,json=orderTagId,proto3" json:"order_tag_id,omitempty"`
	Strategy            string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	OrderTagFilterEvent OrderTagFilterEvent    `protobuf:"varint,101,opt,name=order_tag_filter_event,json=orderTagFilterEvent,proto3,enum=protos.sort.sortmistake.OrderTagFilterEvent" json:"order_tag_filter_event,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderTagFilter) Reset() {
	*x = OrderTagFilter{}
	mi := &file_sort_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTagFilter) ProtoMessage() {}

func (x *OrderTagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTagFilter.ProtoReflect.Descriptor instead.
func (*OrderTagFilter) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{6}
}

func (x *OrderTagFilter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderTagFilter) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *OrderTagFilter) GetHubId() int64 {
	if x != nil {
		return x.HubId
	}
	return 0
}

func (x *OrderTagFilter) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *OrderTagFilter) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *OrderTagFilter) GetOrderTagId() int64 {
	if x != nil {
		return x.OrderTagId
	}
	return 0
}

func (x *OrderTagFilter) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *OrderTagFilter) GetOrderTagFilterEvent() OrderTagFilterEvent {
	if x != nil {
		return x.OrderTagFilterEvent
	}
	return OrderTagFilterEvent_ORDER_TAG_FILTER_EVENT_UNSPECIFIED
}

type OutputNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemId        string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	HubId           int64                  `protobuf:"varint,3,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	OutputHubId     int64                  `protobuf:"varint,4,opt,name=output_hub_id,json=outputHubId,proto3" json:"output_hub_id,omitempty"`
	ZoneId          int64                  `protobuf:"varint,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneType        string                 `protobuf:"bytes,6,opt,name=zone_type,json=zoneType,proto3" json:"zone_type,omitempty"`
	OutputNodeEvent OutputNodeEvent        `protobuf:"varint,101,opt,name=output_node_event,json=outputNodeEvent,proto3,enum=protos.sort.sortmistake.OutputNodeEvent" json:"output_node_event,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutputNode) Reset() {
	*x = OutputNode{}
	mi := &file_sort_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputNode) ProtoMessage() {}

func (x *OutputNode) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputNode.ProtoReflect.Descriptor instead.
func (*OutputNode) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{7}
}

func (x *OutputNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OutputNode) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *OutputNode) GetHubId() int64 {
	if x != nil {
		return x.HubId
	}
	return 0
}

func (x *OutputNode) GetOutputHubId() int64 {
	if x != nil {
		return x.OutputHubId
	}
	return 0
}

func (x *OutputNode) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *OutputNode) GetZoneType() string {
	if x != nil {
		return x.ZoneType
	}
	return ""
}

func (x *OutputNode) GetOutputNodeEvent() OutputNodeEvent {
	if x != nil {
		return x.OutputNodeEvent
	}
	return OutputNodeEvent_OUTPUT_NODE_EVENT_UNSPECIFIED
}

type SortNodeEvents struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SystemId        string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Type            NodeEventType          `protobuf:"varint,10,opt,name=type,proto3,enum=protos.sort.sortmistake.NodeEventType" json:"type,omitempty"`
	Node            []*SortNode            `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	Path            []*SortPath            `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	ZoneFilter      []*ZoneFilter          `protobuf:"bytes,3,rep,name=zoneFilter,proto3" json:"zoneFilter,omitempty"`
	OutputNode      []*OutputNode          `protobuf:"bytes,4,rep,name=outputNode,proto3" json:"outputNode,omitempty"`
	OrderTagFilters []*OrderTagFilter      `protobuf:"bytes,5,rep,name=orderTagFilters,proto3" json:"orderTagFilters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SortNodeEvents) Reset() {
	*x = SortNodeEvents{}
	mi := &file_sort_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortNodeEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortNodeEvents) ProtoMessage() {}

func (x *SortNodeEvents) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortNodeEvents.ProtoReflect.Descriptor instead.
func (*SortNodeEvents) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{8}
}

func (x *SortNodeEvents) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortNodeEvents) GetType() NodeEventType {
	if x != nil {
		return x.Type
	}
	return NodeEventType_NODE_EVENT_TYPE_UNSPECIFIED
}

func (x *SortNodeEvents) GetNode() []*SortNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SortNodeEvents) GetPath() []*SortPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SortNodeEvents) GetZoneFilter() []*ZoneFilter {
	if x != nil {
		return x.ZoneFilter
	}
	return nil
}

func (x *SortNodeEvents) GetOutputNode() []*OutputNode {
	if x != nil {
		return x.OutputNode
	}
	return nil
}

func (x *SortNodeEvents) GetOrderTagFilters() []*OrderTagFilter {
	if x != nil {
		return x.OrderTagFilters
	}
	return nil
}

type SortMapEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Sortmap       []*SortMap             `protobuf:"bytes,1,rep,name=sortmap,proto3" json:"sortmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortMapEvents) Reset() {
	*x = SortMapEvents{}
	mi := &file_sort_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortMapEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortMapEvents) ProtoMessage() {}

func (x *SortMapEvents) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortMapEvents.ProtoReflect.Descriptor instead.
func (*SortMapEvents) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{9}
}

func (x *SortMapEvents) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortMapEvents) GetSortmap() []*SortMap {
	if x != nil {
		return x.Sortmap
	}
	return nil
}

type SortMapGenerate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      string                 `protobuf:"bytes,9,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	ZoneNode      *SortNode              `protobuf:"bytes,1,opt,name=zone_node,json=zoneNode,proto3" json:"zone_node,omitempty"`
	Path          []*SortPath            `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	SortMap       []*SortMap             `protobuf:"bytes,3,rep,name=sort_map,json=sortMap,proto3" json:"sort_map,omitempty"`
	MapError      MapError               `protobuf:"varint,100,opt,name=map_error,json=mapError,proto3,enum=protos.sort.sortmistake.MapError" json:"map_error,omitempty"`
	Version       int32                  `protobuf:"varint,101,opt,name=version,proto3" json:"version,omitempty"`
	RetryCount    int32                  `protobuf:"varint,102,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryDatetime uint64                 `protobuf:"varint,103,opt,name=retry_datetime,json=retryDatetime,proto3" json:"retry_datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortMapGenerate) Reset() {
	*x = SortMapGenerate{}
	mi := &file_sort_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortMapGenerate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortMapGenerate) ProtoMessage() {}

func (x *SortMapGenerate) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortMapGenerate.ProtoReflect.Descriptor instead.
func (*SortMapGenerate) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{10}
}

func (x *SortMapGenerate) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SortMapGenerate) GetZoneNode() *SortNode {
	if x != nil {
		return x.ZoneNode
	}
	return nil
}

func (x *SortMapGenerate) GetPath() []*SortPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *SortMapGenerate) GetSortMap() []*SortMap {
	if x != nil {
		return x.SortMap
	}
	return nil
}

func (x *SortMapGenerate) GetMapError() MapError {
	if x != nil {
		return x.MapError
	}
	return MapError_MAP_ERROR_UNSPECIFIED
}

func (x *SortMapGenerate) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SortMapGenerate) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SortMapGenerate) GetRetryDatetime() uint64 {
	if x != nil {
		return x.RetryDatetime
	}
	return 0
}

type IntraCachingPathCondition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DestinationId    int64                  `protobuf:"varint,1,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	RejectConditions int32                  `protobuf:"varint,2,opt,name=reject_conditions,json=rejectConditions,proto3" json:"reject_conditions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IntraCachingPathCondition) Reset() {
	*x = IntraCachingPathCondition{}
	mi := &file_sort_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntraCachingPathCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntraCachingPathCondition) ProtoMessage() {}

func (x *IntraCachingPathCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntraCachingPathCondition.ProtoReflect.Descriptor instead.
func (*IntraCachingPathCondition) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{11}
}

func (x *IntraCachingPathCondition) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *IntraCachingPathCondition) GetRejectConditions() int32 {
	if x != nil {
		return x.RejectConditions
	}
	return 0
}

type IntraCachingPathConditionList struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Paths         []*IntraCachingPathCondition `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntraCachingPathConditionList) Reset() {
	*x = IntraCachingPathConditionList{}
	mi := &file_sort_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntraCachingPathConditionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntraCachingPathConditionList) ProtoMessage() {}

func (x *IntraCachingPathConditionList) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntraCachingPathConditionList.ProtoReflect.Descriptor instead.
func (*IntraCachingPathConditionList) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{12}
}

func (x *IntraCachingPathConditionList) GetPaths() []*IntraCachingPathCondition {
	if x != nil {
		return x.Paths
	}
	return nil
}

type IntraCachingOutputNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        []int64                `protobuf:"varint,1,rep,packed,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntraCachingOutputNode) Reset() {
	*x = IntraCachingOutputNode{}
	mi := &file_sort_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntraCachingOutputNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntraCachingOutputNode) ProtoMessage() {}

func (x *IntraCachingOutputNode) ProtoReflect() protoreflect.Message {
	mi := &file_sort_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntraCachingOutputNode.ProtoReflect.Descriptor instead.
func (*IntraCachingOutputNode) Descriptor() ([]byte, []int) {
	return file_sort_node_proto_rawDescGZIP(), []int{13}
}

func (x *IntraCachingOutputNode) GetZoneId() []int64 {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

var File_sort_node_proto protoreflect.FileDescriptor

const file_sort_node_proto_rawDesc = "" +
	"\n" +
	"\x0fsort_node.proto\x12\x17protos.sort.sortmistake\"\xc6\x03\n" +
	"\bSortNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\areal_id\x18\x03 \x01(\x03R\x06realId\x12\x15\n" +
	"\x06hub_id\x18\x04 \x01(\x03R\x05hubId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x125\n" +
	"\x04type\x18\x06 \x01(\x0e2!.protos.sort.sortmistake.NodeTypeR\x04type\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12-\n" +
	"\x12rejection_criteria\x18\v \x01(\rR\x11rejectionCriteria\x12\x1b\n" +
	"\tcompat_id\x183 \x01(\x03R\bcompatId\x12A\n" +
	"\n" +
	"node_event\x18e \x01(\x0e2\".protos.sort.sortmistake.NodeEventR\tnodeEvent\x129\n" +
	"\x05error\x18\xc8\x01 \x01(\x0e2\".protos.sort.sortmistake.NodeErrorR\x05error\x12 \n" +
	"\vretry_count\x18\xca\x01 \x01(\x05R\n" +
	"retryCount\x12&\n" +
	"\x0eretry_datetime\x18\xcb\x01 \x01(\x04R\rretryDatetime\"\xa6\x04\n" +
	"\bSortPath\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\x03R\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x02 \x01(\x03R\x11destinationNodeId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12\x15\n" +
	"\x06hub_id\x18\x05 \x01(\x03R\x05hubId\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12\x1a\n" +
	"\bdistance\x18\n" +
	" \x01(\rR\bdistance\x121\n" +
	"\x14rejection_conditions\x18\v \x01(\rR\x13rejectionConditions\x12%\n" +
	"\fzone_filters\x18\f \x03(\x03B\x02\x18\x01R\vzoneFilters\x12\x14\n" +
	"\x05label\x18\x15 \x01(\tR\x05label\x12Q\n" +
	"\x10zone_filter_refs\x18\x16 \x03(\v2'.protos.sort.sortmistake.PathZoneFilterR\x0ezoneFilterRefs\x12^\n" +
	"\x15order_tag_filter_refs\x18\x17 \x03(\v2+.protos.sort.sortmistake.PathOrderTagFilterR\x12orderTagFilterRefs\x12A\n" +
	"\n" +
	"path_event\x18e \x01(\x0e2\".protos.sort.sortmistake.PathEventR\tpathEvent\"F\n" +
	"\x0ePathZoneFilter\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\x03R\x06zoneId\x12\x1b\n" +
	"\tzone_type\x18\x02 \x01(\tR\bzoneType\"R\n" +
	"\x12PathOrderTagFilter\x12 \n" +
	"\forder_tag_id\x18\x01 \x01(\x03R\n" +
	"orderTagId\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\"\x89\x03\n" +
	"\aSortMap\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\x03R\x06zoneId\x12 \n" +
	"\fzone_node_id\x18\x02 \x01(\x03R\n" +
	"zoneNodeId\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\x03R\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x06 \x01(\x03R\x11destinationNodeId\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12\x1a\n" +
	"\bdistance\x18\n" +
	" \x01(\rR\bdistance\x12+\n" +
	"\x11adjusted_distance\x18\v \x01(\rR\x10adjustedDistance\x121\n" +
	"\x14rejection_conditions\x18\f \x01(\rR\x13rejectionConditions\x12\x14\n" +
	"\x05label\x18\x15 \x01(\tR\x05label\x12>\n" +
	"\tmap_event\x18e \x01(\x0e2!.protos.sort.sortmistake.MapEventR\bmapEvent\"\xd7\x02\n" +
	"\n" +
	"ZoneFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x15\n" +
	"\x06hub_id\x18\x03 \x01(\x03R\x05hubId\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\x03R\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x05 \x01(\x03R\rdestinationId\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\x03R\x06zoneId\x125\n" +
	"\x17ref_reject_condition_id\x18\a \x01(\x03R\x14refRejectConditionId\x12\x1b\n" +
	"\tzone_type\x18\b \x01(\tR\bzoneType\x12T\n" +
	"\x11zone_filter_event\x18e \x01(\x0e2(.protos.sort.sortmistake.ZoneFilterEventR\x0fzoneFilterEvent\"\xb9\x02\n" +
	"\x0eOrderTagFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x15\n" +
	"\x06hub_id\x18\x03 \x01(\x03R\x05hubId\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\x03R\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x05 \x01(\x03R\rdestinationId\x12 \n" +
	"\forder_tag_id\x18\x06 \x01(\x03R\n" +
	"orderTagId\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x12a\n" +
	"\x16order_tag_filter_event\x18e \x01(\x0e2,.protos.sort.sortmistake.OrderTagFilterEventR\x13orderTagFilterEvent\"\x80\x02\n" +
	"\n" +
	"OutputNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x15\n" +
	"\x06hub_id\x18\x03 \x01(\x03R\x05hubId\x12\"\n" +
	"\routput_hub_id\x18\x04 \x01(\x03R\voutputHubId\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\x03R\x06zoneId\x12\x1b\n" +
	"\tzone_type\x18\x06 \x01(\tR\bzoneType\x12T\n" +
	"\x11output_node_event\x18e \x01(\x0e2(.protos.sort.sortmistake.OutputNodeEventR\x0foutputNodeEvent\"\xb4\x03\n" +
	"\x0eSortNodeEvents\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12:\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2&.protos.sort.sortmistake.NodeEventTypeR\x04type\x125\n" +
	"\x04node\x18\x01 \x03(\v2!.protos.sort.sortmistake.SortNodeR\x04node\x125\n" +
	"\x04path\x18\x02 \x03(\v2!.protos.sort.sortmistake.SortPathR\x04path\x12C\n" +
	"\n" +
	"zoneFilter\x18\x03 \x03(\v2#.protos.sort.sortmistake.ZoneFilterR\n" +
	"zoneFilter\x12C\n" +
	"\n" +
	"outputNode\x18\x04 \x03(\v2#.protos.sort.sortmistake.OutputNodeR\n" +
	"outputNode\x12Q\n" +
	"\x0forderTagFilters\x18\x05 \x03(\v2'.protos.sort.sortmistake.OrderTagFilterR\x0forderTagFilters\"h\n" +
	"\rSortMapEvents\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12:\n" +
	"\asortmap\x18\x01 \x03(\v2 .protos.sort.sortmistake.SortMapR\asortmap\"\x84\x03\n" +
	"\x0fSortMapGenerate\x12\x1b\n" +
	"\tsystem_id\x18\t \x01(\tR\bsystemId\x12>\n" +
	"\tzone_node\x18\x01 \x01(\v2!.protos.sort.sortmistake.SortNodeR\bzoneNode\x125\n" +
	"\x04path\x18\x02 \x03(\v2!.protos.sort.sortmistake.SortPathR\x04path\x12;\n" +
	"\bsort_map\x18\x03 \x03(\v2 .protos.sort.sortmistake.SortMapR\asortMap\x12>\n" +
	"\tmap_error\x18d \x01(\x0e2!.protos.sort.sortmistake.MapErrorR\bmapError\x12\x18\n" +
	"\aversion\x18e \x01(\x05R\aversion\x12\x1f\n" +
	"\vretry_count\x18f \x01(\x05R\n" +
	"retryCount\x12%\n" +
	"\x0eretry_datetime\x18g \x01(\x04R\rretryDatetime\"o\n" +
	"\x19IntraCachingPathCondition\x12%\n" +
	"\x0edestination_id\x18\x01 \x01(\x03R\rdestinationId\x12+\n" +
	"\x11reject_conditions\x18\x02 \x01(\x05R\x10rejectConditions\"i\n" +
	"\x1dIntraCachingPathConditionList\x12H\n" +
	"\x05paths\x18\x01 \x03(\v22.protos.sort.sortmistake.IntraCachingPathConditionR\x05paths\"1\n" +
	"\x16IntraCachingOutputNode\x12\x17\n" +
	"\azone_id\x18\x01 \x03(\x03R\x06zoneId*\xb2\x01\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rNODE_TYPE_HUB\x10\x01\x12\x14\n" +
	"\x10NODE_TYPE_MIDDLE\x10\x02\x12\x12\n" +
	"\x0eNODE_TYPE_ZONE\x10\x03\x12\x19\n" +
	"\x15NODE_TYPE_INTRA_INPUT\x10\x04\x12\x17\n" +
	"\x13NODE_TYPE_INTRA_MID\x10\x05\x12\x1a\n" +
	"\x16NODE_TYPE_INTRA_OUTPUT\x10\x06*o\n" +
	"\tNodeEvent\x12\x1a\n" +
	"\x16NODE_EVENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_EVENT_CREATED\x10\x01\x12\x16\n" +
	"\x12NODE_EVENT_UPDATED\x10\x02\x12\x16\n" +
	"\x12NODE_EVENT_DELETED\x10\x03*l\n" +
	"\rNodeEventType\x12\x1f\n" +
	"\x1bNODE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NODE_EVENT_TYPE_INTERNAL\x10\x01\x12\x1c\n" +
	"\x18NODE_EVENT_TYPE_EXTERNAL\x10\x02*l\n" +
	"\tNodeError\x12\x1a\n" +
	"\x16NODE_ERROR_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_ERROR_DATABASE\x10\x01\x12\x14\n" +
	"\x10NODE_ERROR_REDIS\x10\x02\x12\x14\n" +
	"\x10NODE_ERROR_KAFKA\x10\x03*o\n" +
	"\tPathEvent\x12\x1a\n" +
	"\x16PATH_EVENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PATH_EVENT_CREATED\x10\x01\x12\x16\n" +
	"\x12PATH_EVENT_UPDATED\x10\x02\x12\x16\n" +
	"\x12PATH_EVENT_DELETED\x10\x03*\x91\x01\n" +
	"\x0fZoneFilterEvent\x12!\n" +
	"\x1dZONE_FILTER_EVENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ZONE_FILTER_EVENT_CREATED\x10\x01\x12\x1d\n" +
	"\x19ZONE_FILTER_EVENT_UPDATED\x10\x02\x12\x1d\n" +
	"\x19ZONE_FILTER_EVENT_DELETED\x10\x03*\xa9\x01\n" +
	"\x13OrderTagFilterEvent\x12&\n" +
	"\"ORDER_TAG_FILTER_EVENT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eORDER_TAG_FILTER_EVENT_CREATED\x10\x01\x12\"\n" +
	"\x1eORDER_TAG_FILTER_EVENT_UPDATED\x10\x02\x12\"\n" +
	"\x1eORDER_TAG_FILTER_EVENT_DELETED\x10\x03*\x91\x01\n" +
	"\x0fOutputNodeEvent\x12!\n" +
	"\x1dOUTPUT_NODE_EVENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OUTPUT_NODE_EVENT_CREATED\x10\x01\x12\x1d\n" +
	"\x19OUTPUT_NODE_EVENT_UPDATED\x10\x02\x12\x1d\n" +
	"\x19OUTPUT_NODE_EVENT_DELETED\x10\x03*j\n" +
	"\bMapEvent\x12\x19\n" +
	"\x15MAP_EVENT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MAP_EVENT_CREATED\x10\x01\x12\x15\n" +
	"\x11MAP_EVENT_UPDATED\x10\x02\x12\x15\n" +
	"\x11MAP_EVENT_DELETED\x10\x03*i\n" +
	"\bMapError\x12\x19\n" +
	"\x15MAP_ERROR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MAP_ERROR_GENERATE\x10\x01\x12\x13\n" +
	"\x0fMAP_ERROR_STORE\x10\x02\x12\x15\n" +
	"\x11MAP_ERROR_PUBLISH\x10\x03Bi\n" +
	"#co.ninjavan.protos.sort.sortmistakeB\vSortMistakeZ5bitbucket.ninjavan.co/sort/sort-protos/go/sortmistakeb\x06proto3"

var (
	file_sort_node_proto_rawDescOnce sync.Once
	file_sort_node_proto_rawDescData []byte
)

func file_sort_node_proto_rawDescGZIP() []byte {
	file_sort_node_proto_rawDescOnce.Do(func() {
		file_sort_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sort_node_proto_rawDesc), len(file_sort_node_proto_rawDesc)))
	})
	return file_sort_node_proto_rawDescData
}

var file_sort_node_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_sort_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sort_node_proto_goTypes = []any{
	(NodeType)(0),                         // 0: protos.sort.sortmistake.NodeType
	(NodeEvent)(0),                        // 1: protos.sort.sortmistake.NodeEvent
	(NodeEventType)(0),                    // 2: protos.sort.sortmistake.NodeEventType
	(NodeError)(0),                        // 3: protos.sort.sortmistake.NodeError
	(PathEvent)(0),                        // 4: protos.sort.sortmistake.PathEvent
	(ZoneFilterEvent)(0),                  // 5: protos.sort.sortmistake.ZoneFilterEvent
	(OrderTagFilterEvent)(0),              // 6: protos.sort.sortmistake.OrderTagFilterEvent
	(OutputNodeEvent)(0),                  // 7: protos.sort.sortmistake.OutputNodeEvent
	(MapEvent)(0),                         // 8: protos.sort.sortmistake.MapEvent
	(MapError)(0),                         // 9: protos.sort.sortmistake.MapError
	(*SortNode)(nil),                      // 10: protos.sort.sortmistake.SortNode
	(*SortPath)(nil),                      // 11: protos.sort.sortmistake.SortPath
	(*PathZoneFilter)(nil),                // 12: protos.sort.sortmistake.PathZoneFilter
	(*PathOrderTagFilter)(nil),            // 13: protos.sort.sortmistake.PathOrderTagFilter
	(*SortMap)(nil),                       // 14: protos.sort.sortmistake.SortMap
	(*ZoneFilter)(nil),                    // 15: protos.sort.sortmistake.ZoneFilter
	(*OrderTagFilter)(nil),                // 16: protos.sort.sortmistake.OrderTagFilter
	(*OutputNode)(nil),                    // 17: protos.sort.sortmistake.OutputNode
	(*SortNodeEvents)(nil),                // 18: protos.sort.sortmistake.SortNodeEvents
	(*SortMapEvents)(nil),                 // 19: protos.sort.sortmistake.SortMapEvents
	(*SortMapGenerate)(nil),               // 20: protos.sort.sortmistake.SortMapGenerate
	(*IntraCachingPathCondition)(nil),     // 21: protos.sort.sortmistake.IntraCachingPathCondition
	(*IntraCachingPathConditionList)(nil), // 22: protos.sort.sortmistake.IntraCachingPathConditionList
	(*IntraCachingOutputNode)(nil),        // 23: protos.sort.sortmistake.IntraCachingOutputNode
}
var file_sort_node_proto_depIdxs = []int32{
	0,  // 0: protos.sort.sortmistake.SortNode.type:type_name -> protos.sort.sortmistake.NodeType
	1,  // 1: protos.sort.sortmistake.SortNode.node_event:type_name -> protos.sort.sortmistake.NodeEvent
	3,  // 2: protos.sort.sortmistake.SortNode.error:type_name -> protos.sort.sortmistake.NodeError
	12, // 3: protos.sort.sortmistake.SortPath.zone_filter_refs:type_name -> protos.sort.sortmistake.PathZoneFilter
	13, // 4: protos.sort.sortmistake.SortPath.order_tag_filter_refs:type_name -> protos.sort.sortmistake.PathOrderTagFilter
	4,  // 5: protos.sort.sortmistake.SortPath.path_event:type_name -> protos.sort.sortmistake.PathEvent
	8,  // 6: protos.sort.sortmistake.SortMap.map_event:type_name -> protos.sort.sortmistake.MapEvent
	5,  // 7: protos.sort.sortmistake.ZoneFilter.zone_filter_event:type_name -> protos.sort.sortmistake.ZoneFilterEvent
	6,  // 8: protos.sort.sortmistake.OrderTagFilter.order_tag_filter_event:type_name -> protos.sort.sortmistake.OrderTagFilterEvent
	7,  // 9: protos.sort.sortmistake.OutputNode.output_node_event:type_name -> protos.sort.sortmistake.OutputNodeEvent
	2,  // 10: protos.sort.sortmistake.SortNodeEvents.type:type_name -> protos.sort.sortmistake.NodeEventType
	10, // 11: protos.sort.sortmistake.SortNodeEvents.node:type_name -> protos.sort.sortmistake.SortNode
	11, // 12: protos.sort.sortmistake.SortNodeEvents.path:type_name -> protos.sort.sortmistake.SortPath
	15, // 13: protos.sort.sortmistake.SortNodeEvents.zoneFilter:type_name -> protos.sort.sortmistake.ZoneFilter
	17, // 14: protos.sort.sortmistake.SortNodeEvents.outputNode:type_name -> protos.sort.sortmistake.OutputNode
	16, // 15: protos.sort.sortmistake.SortNodeEvents.orderTagFilters:type_name -> protos.sort.sortmistake.OrderTagFilter
	14, // 16: protos.sort.sortmistake.SortMapEvents.sortmap:type_name -> protos.sort.sortmistake.SortMap
	10, // 17: protos.sort.sortmistake.SortMapGenerate.zone_node:type_name -> protos.sort.sortmistake.SortNode
	11, // 18: protos.sort.sortmistake.SortMapGenerate.path:type_name -> protos.sort.sortmistake.SortPath
	14, // 19: protos.sort.sortmistake.SortMapGenerate.sort_map:type_name -> protos.sort.sortmistake.SortMap
	9,  // 20: protos.sort.sortmistake.SortMapGenerate.map_error:type_name -> protos.sort.sortmistake.MapError
	21, // 21: protos.sort.sortmistake.IntraCachingPathConditionList.paths:type_name -> protos.sort.sortmistake.IntraCachingPathCondition
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_sort_node_proto_init() }
func file_sort_node_proto_init() {
	if File_sort_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sort_node_proto_rawDesc), len(file_sort_node_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sort_node_proto_goTypes,
		DependencyIndexes: file_sort_node_proto_depIdxs,
		EnumInfos:         file_sort_node_proto_enumTypes,
		MessageInfos:      file_sort_node_proto_msgTypes,
	}.Build()
	File_sort_node_proto = out.File
	file_sort_node_proto_goTypes = nil
	file_sort_node_proto_depIdxs = nil
}
