podman:
  bin: /opt/podman/bin/podman
  images:
    mysql: "mysql:8.0"
    kafka: "confluentinc/confluent-local:7.6.0"
    redis: "redis:7-alpine"
    wiremock: "docker.io/wiremock/wiremock:3.5.2"
    flyway: "docker.io/flyway/flyway:11-alpine"
